### ISSUE TITLE
Show better error when trying to log in with a user that doesn't exist

### ISSUE THREAD

**Issue by Eldemarkki** [Testaustime/testaustime-backend#56]
Currently it throws a Diesel error if trying to log in with a non-existent user:
`curl 'https://api.testaustime.fi/auth/login' -X POST -H 'Content-Type: application/json' --data-raw '{"username":"thisuserdoesntexist","password":"thisuserdoesntexist"}'` returns ```{"error":"Diesel transaction failed `Record not found`"}```. It should instead return a generic error, such as `{"error":"Invalid credentials"}`

Note that those specific credentials may start working if someone creates that user after seeing this issue. This can be bypassed by purchasing a cat and making it run over your keyboard to generate a new, hopefully non-existent user.

Partially fixes https://github.com/Testaustime/testaustime-frontend/issues/63 also.

**Comment by lajp** [comment]
@Eldemarkki I think here we could just return `TimeError::UserNotFound` if no such user exists. Do you agree?

**Comment by Eldemarkki** [comment]
@lajp  The OWASP guidelines discourage that type of response. See this page: https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#login. I would follow those guidelines and send a generic response.

> Incorrect response examples:
>  - "Login for User foo: invalid password."
>  - **"Login failed, invalid user ID."**
>  - "Login failed; account disabled."
>  - "Login failed; this user is not active."
> 
> Correct response example:
>  - **"Login failed; Invalid user ID or password."**

**Comment by lajp** [comment]
So it shall be then

**Comment by lajp** [comment]
![image](https://user-images.githubusercontent.com/31856315/202908540-c09f15ba-f1d2-4067-bacf-c5a5258ed723.png)
just to make sure that this is how you want it?

**Comment by lajp** [comment]
And what would be the correct http status code for this response?

**Comment by Eldemarkki** [comment]
Yep that’s good. Probably `401 Unauthorized` would be the most appropriate

**Comment by Eldemarkki** [comment]
Fixed
