### ISSUE TITLE
Better error if a user doesn't have a current activity

### ISSUE THREAD

**Issue by Eldemarkki** [Testaustime/testaustime-backend#65]
If a user doesn't have a current activity, but their current activity is requested at `/users/USERNAME/activity/current`, it will just return `null` with status 200. 

```bash
$ curl 'https://api.testaustime.fi/users/Antti/activity/current' -H 'Authorization: Bearer REDACTED'
null
```

(sorry Antti for exposing your inactivity)

I suggest we return some JSON (e.g. `{"error":"User doesn't have an active session"}`) with status code 404.

**Comment by lajp** [comment]
Ok, will do :)
