### ISSUE TITLE
Create route to get aggregated data about the whole instance

### ISSUE THREAD

**Issue by Eldemarkki** [Testaustime/testaustime-backend#75]
The info could be, for example 
- Total time coded (among all users)
- Most used programming language (among all users)
- User count

The privacy implications of this should be considered as well. Should this for example be only opt-in? 

For the people who might self-host Testaustime (not sure if there are any at the moment), it should also be possible for the admins to disable these data routes via e.g. an environment variable.

**Comment by lajp** [comment]
I actually made this at some point but forgot to make a PR :D.
I'll find the code and make a PR later today
