### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by Chicken** [Testaustime/testaustime-backend#9]
Update the API documentation.
If feeling extra fancy, create a new tool which auto generates the documentation from comments in the code and just write a doc comment above the endpoint in the code when implementing new features.

**Comment by DrVilepis** [comment]
This might take a while to fix, as we are looking into a better apidoc format such as openapi

**Comment by Merkush1** [comment]
Hey guys, i saw that you have some endpoints not documented in https://github.com/Testaustime/testaustime-backend/blob/main/docs/APISPEC.md 

So can i document for example some new endpoints like friends/remove, activity/delete and etc?

 For the first step i can update endpoints for the first PR in your [current page](https://github.com/Testaustime/testaustime-backend/blob/main/docs/APISPEC.md ). For the second - add some Swagger (OpenAPI)

**Comment by DrVilepis** [comment]
Feel free, we aren't really interested in writing documentation right now so it would be great if you could document them.

The OpenAPI format would also be very nice, this would be greatly appreciated.

**Comment by lajp** [comment]
@Merkush1 also beware that some of the documentation in [APISPEC.md](/docs/APISPEC.md) might not match the functionality that the endpoints have now. So don't trust the existing apispec.

**Comment by zahertalab** [comment]
How to contribute?

**Comment by lajp** [comment]
Thank you for showing interest in this project.
Our contribution guidelines can be found [here](/docs/CONTRIBUTING.md)

Our existing API-documentation recently written by Merkush1 can be found [here](/docs/APISPEC.md).

Even tough there's always something that can be improved in documentation, I feel that with #40 merged we can happily close this issue. If @zahertalab or anyone else wants to improve upon the existing documentation or wants further clarification on how a specific endpoint functions, they can always open a new PR/issue.

**Comment by zahertalab** [comment]
> Thank you for showing interest in this project. Our contribution guidelines can be found [here](/docs/CONTRIBUTING.md)
> 
> Our existing API-documentation recently written by Merkush1 can be found [here](/docs/APISPEC.md).
> 
> Even tough there's always something that can be improved in documentation, I feel that with #40 merged we can happily close this issue. If @zahertalab or anyone else wants to improve upon the existing documentation or wants further clarification on how a specific endpoint functions, they can always open a new PR/issue.

I'd like to improve upon the existing documentation. But the links you have put are broken.

**Comment by bluelhf** [comment]
> > Thank you for showing interest in this project. Our contribution guidelines can be found [here](/docs/CONTRIBUTING.md)
> > Our existing API-documentation recently written by Merkush1 can be found [here](/docs/APISPEC.md).
> > Even tough there's always something that can be improved in documentation, I feel that with #40 merged we can happily close this issue. If @zahertalab or anyone else wants to improve upon the existing documentation or wants further clarification on how a specific endpoint functions, they can always open a new PR/issue.
> 
> I'd like to improve upon the existing documentation. But the links you have put are broken.

Here are the correct links to the [API specification](https://github.com/Testaustime/testaustime-backend/blob/main/docs/APISPEC.md) and [contribution guidelines](https://github.com/Testaustime/testaustime-backend/blob/main/docs/CONTRIBUTING.md) :)
