### ISSUE TITLE
`/leaderboards/{name}/regenerate` innecessarily requires an empty body

### ISSUE THREAD

**Issue by Eldemarkki** [Testaustime/testaustime-backend#93]
If I do `curl --request POST "https://api.testaustime.fi/leaderboards/[redacted]/regenerate" --header "Authorization: Bearer [redacted]"` it will return 400 Bad Request, even though the API spec says that that is okay.

I must instead do `curl --request POST "https://api.testaustime.fi/leaderboards/[redacted]/regenerate" --header "Authorization: Bearer [redacted]" -H "Content-Type: application/json" --data-raw ""` to get it to regenerate the token.

We should ideally not require any body, or at least update the API spec to include this requirement.

**Comment by lajp** [comment]
Can't reproduce on current HEAD
